inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance
  - standard/cop/block_single_line_braces  

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop-rails.yml
  - .rubocop-rspec.yml
  
# Standardrb overrides
Layout/HashAlignment:
  Description: 'in multi-line hash definitions, aligns keys and values in a table-like layout'
  EnforcedHashRocketStyle: table

Style/RedundantInterpolation:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
