require: 
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec

Bundler/OrderedGems:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Rails/RakeEnvironment:
  Enabled: false
