name: specs

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        #  don't get ahead of heroku (usually behind AWS, who we also stay behind)
        # https://devcenter.heroku.com/articles/heroku-postgres-version-support
        image: postgres:15.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bunhdler-cache: true

    - name: Setup DB, Run tests
      env:
        RAILS_ENV: test
        PG_USER: postgres
      run: |
        bundle exec rake db:test:prepare
        bundle exec rspec
